export const IPC_CHANNELS = {
  appBootstrap: 'app:bootstrap',
  appGetInfo: 'app:get-info',
  sitesUpsert: 'sites:upsert',
  sitesDelete: 'sites:delete',
  activityClear: 'activity:clear',
  actionsCopyLink: 'actions:copy-link',
  actionsRecordSuccess: 'actions:record-success',
  actionsUndoSuccess: 'actions:undo-success',
  settingsSetImageCleanerEnabled: 'settings:set-image-cleaner-enabled',
  settingsSelectImageCleanerFolder: 'settings:select-image-cleaner-folder',
  settingsSetHotkeys: 'settings:set-hotkeys',
  hotkeyTriggered: 'hotkeys:triggered',
  windowMinimize: 'window:minimize',
  imageCleanerCompleted: 'image-cleaner:completed',
  tasksUpsertCategory: 'tasks:upsert-category',
  tasksDeleteCategory: 'tasks:delete-category',
  tasksSetCompletion: 'tasks:set-completion',
  tasksSetCompletions: 'tasks:set-completions',
  externalOpen: 'external:open',
  notificationsShowAction: 'notifications:show-action',
  importerStart: 'importer:start',
  importerCancel: 'importer:cancel',
  importerProgress: 'importer:progress',
  importerCompleted: 'importer:completed',
  checkinStart: 'checkin:start',
  checkinCancel: 'checkin:cancel',
  checkinSaveCredentials: 'checkin:save-credentials',
  checkinDeleteCredentials: 'checkin:delete-credentials',
  checkinCredentialStatus: 'checkin:credential-status',
  checkinProgress: 'checkin:progress',
  checkinCompleted: 'checkin:completed',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
