export const IPC_ERROR_CODES = [
  'VALIDATION_FAILED',
  'UNTRUSTED_SENDER',
  'NOT_FOUND',
  'DAILY_LIMIT_REACHED',
  'ACTION_IN_PROGRESS',
  'PERSISTENCE_FAILED',
  'CLIPBOARD_FAILED',
  'NOTIFICATION_FAILED',
  'EXTERNAL_URL_REJECTED',
  'EXTERNAL_URL_FAILED',
  'FOLDER_SELECTION_FAILED',
  'FOLDER_UNAVAILABLE',
  'UNSAFE_PATH',
  'HOTKEY_REGISTRATION_FAILED',
  'IMAGE_CLEANUP_FAILED',
  'IMPORT_IN_PROGRESS',
  'IMPORT_CANCELLED',
  'IMPORT_TIMEOUT',
  'IMPORT_NETWORK_REJECTED',
  'IMPORT_UNSUPPORTED_PAGE',
  'IMPORT_FAILED',
  'CHECKIN_IN_PROGRESS',
  'CHECKIN_CANCELLED',
  'CHECKIN_TIMEOUT',
  'CHECKIN_NO_CREDENTIALS',
  'CHECKIN_ENCRYPTION_UNAVAILABLE',
  'CHECKIN_LOGIN_FAILED',
  'CHECKIN_FAILED',
  'INTERNAL_ERROR',
] as const;

export type IpcErrorCode = (typeof IPC_ERROR_CODES)[number];

export const IPC_ERROR_CODE_SET: ReadonlySet<IpcErrorCode> = new Set(IPC_ERROR_CODES);

export function isIpcErrorCode(value: string): value is IpcErrorCode {
  return IPC_ERROR_CODE_SET.has(value as IpcErrorCode);
}
