import { APP_STATE_SCHEMA_VERSION, type AppStateV1 } from './app-state';

const DEFAULT_STATE: AppStateV1 = {
  schemaVersion: APP_STATE_SCHEMA_VERSION,
  revision: 0,
  sites: [
    {
      id: 'u2win',
      name: 'U2WIN',
      url: 'https://u2win.online/RFAA15612',
      prefix: '',
      suffix: '',
      dateFormat: 'dd/mm hh:MM',
      bonusCents: 3000,
      maxCopiesPerDay: 2,
    },
    {
      id: 'galaxy',
      name: 'GALAXY',
      url: 'https://galaxyau.com/RF3112A5161',
      prefix: '',
      suffix: '',
      dateFormat: 'dd/mm hh:MM',
      bonusCents: 3000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'space9au',
      name: 'SPACE9AU',
      url: 'https://space9au.com/RF1373A23',
      prefix: '',
      suffix: '🕒',
      dateFormat: 'yyyy-dd-mm hh:MM:ss',
      bonusCents: 2000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'ufo',
      name: 'UFO',
      url: 'https://ufo9.asia/RF168A56376',
      prefix: '',
      suffix: '',
      dateFormat: 'dd/mm hh:MM',
      bonusCents: 2000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'intensity2',
      name: 'INTENSITY2',
      url: 'https://intensity2aus.net/RF377A78377',
      prefix: '🔥Join INTENSITY2 Now!',
      suffix: '',
      dateFormat: 'dd/mm hh:MM',
      bonusCents: 3000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'intensity',
      name: 'INTENSITY',
      url: 'https://intensityaus.com/RF17875138A',
      prefix: '',
      suffix: '',
      dateFormat: 'dd/mm hh:MM',
      bonusCents: 2000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'm9u',
      name: 'M9U',
      url: '',
      prefix: '',
      suffix: '🕒',
      dateFormat: 'yyyy-dd-mm hh:MM:ss',
      bonusCents: 3000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'eq9',
      name: 'EQ9',
      url: 'https://eq9au.com/RF188917A1',
      prefix: '🕒',
      suffix: '',
      dateFormat: 'yyyy-dd-mm hh:MM:ss',
      bonusCents: 3000,
      maxCopiesPerDay: 1,
    },
    {
      id: 'audgo',
      name: 'AUDGO',
      url: 'https://audgo.net/RF222568856',
      prefix: '',
      suffix: '',
      dateFormat: 'dd/mm hh:MM',
      bonusCents: 2800,
      maxCopiesPerDay: 1,
    },
  ],
  dailyRecords: {},
  activity: [],
  settings: {
    darkMode: true,
    imageCleaner: {
      enabled: false,
      folderPath: null,
      hotkey: null,
    },
  },
  taskCategories: [],
  taskDailyRecords: {},
};

export function createDefaultAppState(): AppStateV1 {
  return structuredClone(DEFAULT_STATE);
}
